// files/frameworks/angular/app.component.ts
import { Component } from "@angular/core";
import { ADAPTER_EVENTS, SafeEventEmitterProvider, CHAIN_NAMESPACES } from "@web3auth/base";
import { OpenloginAdapter } from "@web3auth/openlogin-adapter";
import { Web3Auth } from "@web3auth/web3auth";
// REPLACE-web3authChainRpcImport-

const clientId = "YOUR_CLIENT_ID"; // get from https://dashboard.web3auth.io

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "angular-app";
  web3auth: Web3Auth | null = null;
  provider: SafeEventEmitterProvider | null = null;
  isModalLoaded = false;

  async ngOnInit() {
    // REPLACE-const web3AuthInitParams = {};-

    // REPLACE-const web3AuthCtorParams = {};-

    this.web3auth = new Web3Auth(web3AuthCtorParams);

    // REPLACE-const web3AuthOpenloginConfigure = {};-
    this.subscribeAuthEvents(this.web3auth);
    await this.web3auth.initModal(initParams);
    this.isModalLoaded = true;
  }

  subscribeAuthEvents(web3auth: Web3Auth) {
    web3auth.on(ADAPTER_EVENTS.CONNECTED, (data) => {
      console.log("Yeah!, you are successfully logged in", data);
      this.provider = web3auth.provider;
    });

    web3auth.on(ADAPTER_EVENTS.CONNECTING, () => {
      console.log("connecting");
    });

    web3auth.on(ADAPTER_EVENTS.DISCONNECTED, () => {
      console.log("disconnected");
    });

    web3auth.on(ADAPTER_EVENTS.ERRORED, (error) => {
      console.log("some error or user have cancelled login request", error);
    });
  }

  async login() {
    if (!this.web3auth) {
      this.uiConsole("Web3auth is not initialized");
      return;
    }
    this.provider = await this.web3auth.connect();
    this.uiConsole("logged in");
  }

  async logout() {
    if (!this.web3auth) {
      this.uiConsole("Web3auth is not initialized");
      return;
    }
    await this.web3auth.logout();
    this.provider = null;
    this.uiConsole("logged out");
  }

  async getUserInfo() {
    if (!this.web3auth) {
      this.uiConsole("Web3auth is not initialized");
      return;
    }
    const userInfo = await this.web3auth.getUserInfo();
    this.uiConsole("User Info", userInfo);
  }

  async getBalance() {
    if (!this.provider) {
      this.uiConsole("provider is not initialized");
      return;
    }
    const rpc = new RPC(this.provider);
    const balance = await rpc.getBalance();
    this.uiConsole("Balance", balance);
  }

  async getAccount() {
    console.log("GETTING ACCOUNT");
    if (!this.provider) {
      this.uiConsole("provider is not initialized");
      return;
    }
    const rpc = new RPC(this.provider);
    const accounts = await rpc.getAccounts();
    this.uiConsole("Account", accounts);
  }

  async signMessage() {
    if (!this.provider) {
      this.uiConsole("provider is not initialized");
      return;
    }
    const rpc = new RPC(this.provider);
    const res = await rpc.signMessage();
    this.uiConsole("Sign message", res);
  }

  async signTransaction() {
    if (!this.provider) {
      this.uiConsole("provider is not initialized");
      return;
    }
    const rpc = new RPC(this.provider);
    const res = await rpc.signTransaction();
    this.uiConsole("Sign transaction", res);
  }

  async signAndSendTransaction() {
    console.log("SIGNING MESSAGE");
    if (!this.provider) {
      this.uiConsole("provider is not initialized");
      return;
    }
    const rpc = new RPC(this.provider);
    const res = await rpc.signAndSendTransaction();
    this.uiConsole("Sign and send transaction", res);
  }

  uiConsole(...args: unknown[]): void {
    const el = document.querySelector("#console-ui>p");
    if (el) {
      el.innerHTML = JSON.stringify(args || {}, null, 2);
    }
  }
}

<div class="content">
  <h1 class="title">
    <a target="_blank" href="http://web3auth.io/">Web3Auth</a> & AngularJS
    Example
  </h1>
  <div class="setting">
    <div
      *ngIf="isModalLoaded && provider; else elseBlock"
      class="card-container"
    >
      <button class="card card-small" (click)="getUserInfo()">
        Get User Info
      </button>
      <button class="card card-small" (click)="getAccount()">
        Get Account
      </button>
      <button class="card card-small" (click)="getBalance()">
        Get Balance
      </button>
      <button class="card card-small" (click)="signMessage()">
        Sign Message
      </button>
      <button class="card card-small" (click)="signTransaction()">
        Sign Transaction
      </button>
      <button class="card card-small" (click)="signAndSendTransaction()">
        Send Transaction
      </button>
      <button class="card card-small" (click)="logout()">Log Out</button>
      <div class="console" id="console-ui">
        <p class="code">Logged In</p>
      </div>
    </div>
    <ng-template #elseBlock>
      <div class="card-container">
        <button class="card card-small" (click)="login()">Login</button>
      </div>
    </ng-template>
  </div>
  <footer class="footer">
    <a
      href="https://github.com/Web3Auth/Web3Auth/tree/master/examples/angular-app"
      target="_blank"
      rel="noopener noreferrer"
    >
      Source code
      <img class="logo" src="../assets/github-logo.png" />
    </a>
  </footer>
</div>

// files/web3auth/react/custom/App.tsx
import { ADAPTER_EVENTS, CHAIN_NAMESPACES, SafeEventEmitterProvider, WALLET_ADAPTERS } from "@web3auth/base";
import { Web3AuthCore } from "@web3auth/core";
import { OpenloginAdapter } from "@web3auth/openlogin-adapter";
import { useEffect, useState } from "react";
import "./App.css";
// REPLACE-web3authChainRpcImport-

const clientId = "YOUR_CLIENT_ID"; // get from https://dashboard.web3auth.io

function CustomUI() {
  const [web3auth, setWeb3auth] = useState<Web3AuthCore | null>(null);
  const [provider, setProvider] = useState<SafeEventEmitterProvider | null>(null);

  useEffect(() => {
    const init = async () => {
      try {
        // REPLACE-const web3AuthCoreCtorParams = {};-

        const web3auth = new Web3AuthCore(web3AuthCtorParams);

        // REPLACE-const web3AuthOpenloginConfigure = {};-

        subscribeAuthEvents(web3auth);
        setWeb3auth(web3auth);
        await web3auth.init();
      } catch (error) {
        console.error(error);
      }
    };

    const subscribeAuthEvents = (web3auth: Web3AuthCore) => {
      // Can subscribe to all ADAPTER_EVENTS and LOGIN_MODAL_EVENTS
      web3auth.on(ADAPTER_EVENTS.CONNECTED, (data: unknown) => {
        console.log("Yeah!, you are successfully logged in", data);
        setProvider(web3auth.provider);
      });

      web3auth.on(ADAPTER_EVENTS.CONNECTING, () => {
        console.log("connecting");
      });

      web3auth.on(ADAPTER_EVENTS.DISCONNECTED, () => {
        console.log("disconnected");
      });

      web3auth.on(ADAPTER_EVENTS.ERRORED, (error) => {
        console.error("some error or user has cancelled login request", error);
      });
    };

    init();
  }, []);

  const login = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }

    // REPLACE-const web3AuthConnect = {};-

    setProvider(web3authProvider);
  };

  const getUserInfo = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }
    const user = await web3auth.getUserInfo();
    console.log("User info", user);
  };

  const logout = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }
    await web3auth.logout();
    setProvider(null);
  };

  const getAccounts = async () => {
    if (!provider) {
      console.log("provider not initialized yet");
      return;
    }
    const rpc = new RPC(provider);
    const userAccount = await rpc.getAccounts();
    uiConsole(userAccount);
  };

  const getBalance = async () => {
    if (!provider) {
      console.log("provider not initialized yet");
      return;
    }
    const rpc = new RPC(provider);
    const balance = await rpc.getBalance();
    uiConsole(balance);
  };

  const signMessage = async () => {
    if (!provider) {
      console.log("provider not initialized yet");
      return;
    }
    const rpc = new RPC(provider);
    const result = await rpc.signMessage();
    uiConsole(result);
  };

  const signTransaction = async () => {
    if (!provider) {
      uiConsole("provider not initialized yet");
      return;
    }
    const rpc = new RPC(provider);
    const result = await rpc.signTransaction();
    uiConsole(result);
  };

  const sendTransaction = async () => {
    if (!provider) {
      console.log("provider not initialized yet");
      return;
    }
    const rpc = new RPC(provider);
    const result = await rpc.signAndSendTransaction();
    uiConsole(result);
  };

  function uiConsole(...args: any[]): void {
    const el = document.querySelector("#console>p");
    if (el) {
      el.innerHTML = JSON.stringify(args || {}, null, 2);
    }
  }

  const loggedInView = (
    <>
      <button onClick={getUserInfo} className="card">
        Get User Info
      </button>
      <button onClick={getAccounts} className="card">
        Get Accounts
      </button>
      <button onClick={getBalance} className="card">
        Get Balance
      </button>
      <button onClick={signMessage} className="card">
        Sign Message
      </button>
      <button onClick={signTransaction} className="card">
        Sign Transaction
      </button>
      <button onClick={sendTransaction} className="card">
        Send Transaction
      </button>
      <button onClick={logout} className="card">
        Log Out
      </button>

      <div id="console" style={{ whiteSpace: "pre-line" }}>
        <p style={{ whiteSpace: "pre-line" }}></p>
      </div>
    </>
  );

  const unloggedInView = (
    <>
      <button onClick={login} className="card">
        Google Login
      </button>
    </>
  );

  return (
    <div className="container">
      <h1 className="title">
        <a target="_blank" href="http://web3auth.io/" rel="noreferrer">
          Web3Auth
        </a>{" "}
        & ReactJS Example
      </h1>

      <div className="grid">{provider ? loggedInView : unloggedInView}</div>

      <footer className="footer">
        <a href="https://github.com/Web3Auth/Web3Auth/tree/master/examples/react-app" target="_blank" rel="noopener noreferrer">
          Source code {"  "}
          <img className="logo" src="/images/github-logo.png" alt="github-logo" />
        </a>
      </footer>
    </div>
  );
}

export default CustomUI;
