// files/frameworks/angular/app.component.ts
import { Component } from "@angular/core";
// REPLACE-web3authChainRpcImport-

const clientId = "YOUR_CLIENT_ID"; // get from https://dashboard.web3auth.io

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
    title = "angular-app";
    web3auth: Web3Auth | null = null;
    provider: SafeEventEmitterProvider | null = null;
    isModalLoaded = false;

    async ngOnInit() {
      // REPLACE-const web3AuthCtorParams = {};-


      // REPLACE-const web3AuthOpenloginConfigure = {};-


      // REPLACE-const web3AuthInitParams = {};-


      this.isModalLoaded = true;
    }

    login = async () => {
    if (!this.web3auth) {
      this.uiConsole("web3auth not initialized yet");
      return;
    }
    const web3auth = this.web3auth;
      // REPLACE-const web3AuthConnect = {};-

    this.provider = web3authProvider;
    this.uiConsole("logged in");
    };

    getUserInfo = async () => {
      if (!this.web3auth) {
        this.uiConsole("web3auth not initialized yet");
        return;
      }
      const user = await this.web3auth.getUserInfo();
      this.uiConsole(user);
    };

  // REPLACE-rpcFunctionsImport-


    logout = async () => {
      if (!this.web3auth) {
        this.uiConsole("web3auth not initialized yet");
        return;
      }
      await this.web3auth.logout();
      this.provider = null;
      this.uiConsole("logged out");
    };

    uiConsole(...args: unknown[]): void {
      const el = document.querySelector("#console-ui>p");
      if (el) {
        el.innerHTML = JSON.stringify(args || {}, null, 2);
      }
    };
}

<div class="content">
  <h1 class="title"><a target="_blank" href="http://web3auth.io/">Web3Auth</a> & AngularJS Example</h1>
  <div class="setting">
    <div *ngIf="isModalLoaded && provider; else elseBlock" class="card-container">
      <button class="card card-small" (click)="getUserInfo">Get User Info</button>
      // REPLACE-rpcFunctionsUIButtonsImport-

      <button class="card card-small" (click)="logout">Log Out</button>
      <div class="console" id="console-ui">
        <p class="code">Logged In</p>
      </div>
    </div>
    <ng-template #elseBlock>
      <div class="card-container">
        <button class="card card-small" (click)="login">Login</button>
      </div>
    </ng-template>
  </div>
  <footer class="footer">
    <a href="https://github.com/Web3Auth/Web3Auth/tree/master/examples/angular-app" target="_blank" rel="noopener noreferrer"> Source code </a>
  </footer>
</div>

// files/frameworks/nextjs/custom/App.tsx
import { ADAPTER_EVENTS, CHAIN_NAMESPACES, SafeEventEmitterProvider, WALLET_ADAPTERS } from "@web3auth/base";
import { Web3AuthCore } from "@web3auth/core";
import { OpenloginAdapter } from "@web3auth/openlogin-adapter";
import { useEffect, useState } from "react";
import "./App.css";
// REPLACE-web3authChainRpcImport-

const clientId = "YOUR_CLIENT_ID"; // get from https://dashboard.web3auth.io

function CustomUI() {
  const [web3auth, setWeb3auth] = useState<Web3AuthCore | null>(null);
  const [provider, setProvider] = useState<SafeEventEmitterProvider | null>(null);

  useEffect(() => {
    const init = async () => {
      try {
        // REPLACE-const web3AuthCtorParams = {};-

        // REPLACE-const web3AuthOpenloginConfigure = {};-

        setWeb3auth(web3auth);
        // REPLACE-const web3AuthInitParams = {};-
      } catch (error) {
        console.error(error);
      }
    };
    init();
  }, []);

  const login = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }

    // REPLACE-const web3AuthConnect = {};-

    setProvider(web3authProvider);
  };

  const getUserInfo = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }
    const user = await web3auth.getUserInfo();
    uiConsole(user);
  };

  const logout = async () => {
    if (!web3auth) {
      console.log("web3auth not initialized yet");
      return;
    }
    await web3auth.logout();
    setProvider(null);
  };

// REPLACE-rpcFunctionsImport-


  function uiConsole(...args: any[]): void {
    const el = document.querySelector("#console>p");
    if (el) {
      el.innerHTML = JSON.stringify(args || {}, null, 2);
    }
  }

  const loggedInView = (
    <>
      <button onClick={getUserInfo} className="card">
        Get User Info
      </button>
      // REPLACE-rpcFunctionsUIButtonsImport-

      <button onClick={logout} className="card">
        Log Out
      </button>

      <div id="console" style={{ whiteSpace: "pre-line" }}>
        <p style={{ whiteSpace: "pre-line" }}></p>
      </div>
    </>
  );

  const unloggedInView = (
    <>
      <button onClick={login} className="card">
        Login
      </button>
    </>
  );

  return (
    <div className="container">
      <h1 className="title">
        <a target="_blank" href="http://web3auth.io/" rel="noreferrer">
          Web3Auth
        </a>{" "}
        & ReactJS Example
      </h1>

      <div className="grid">{provider ? loggedInView : unloggedInView}</div>

      <footer className="footer">
        <a href="https://github.com/Web3Auth/Web3Auth/tree/master/examples/react-app" target="_blank" rel="noopener noreferrer">
          Source code
        </a>
      </footer>
    </div>
  );
}

export default CustomUI;
